// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241126042611_Version_1")]
    partial class Version_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Entities.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "Author A",
                            BookName = "Book One",
                            Categories = "Fiction, Science, History, Technology, Health",
                            Description = "A great fiction book.",
                            ImagePath = "image1.jpg",
                            Price = 19.99m,
                            PublishedDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publisher X",
                            StockQuantity = 100
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Author B",
                            BookName = "Book Two",
                            Categories = "Fiction, Science, History, Technology, Health",
                            Description = "An insightful science book.",
                            ImagePath = "image2.jpg",
                            Price = 29.99m,
                            PublishedDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publisher Y",
                            StockQuantity = 50
                        },
                        new
                        {
                            BookID = 3,
                            Author = "Author C",
                            BookName = "Book Three",
                            Categories = "Fiction, Science, History, Technology, Health",
                            Description = "A detailed history book.",
                            ImagePath = "image3.jpg",
                            Price = 25.00m,
                            PublishedDate = new DateTime(2019, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publisher Z",
                            StockQuantity = 75
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Author D",
                            BookName = "Book Four",
                            Categories = "Fiction, Science, History, Technology, Health",
                            Description = "An advanced tech book.",
                            ImagePath = "image4.jpg",
                            Price = 15.50m,
                            PublishedDate = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publisher W",
                            StockQuantity = 60
                        },
                        new
                        {
                            BookID = 5,
                            Author = "Author E",
                            BookName = "Book Five",
                            Categories = "Fiction, Science, History, Technology, Health",
                            Description = "A comprehensive health guide.",
                            ImagePath = "image5.jpg",
                            Price = 12.99m,
                            PublishedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Publisher V",
                            StockQuantity = 80
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Fiction"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Science"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "History"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Technology"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Health"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "123 Main St",
                            CCCD = "123456789",
                            Email = "nguyenvana@example.com",
                            FullName = "Nguyen Van A",
                            Password = "12345",
                            Phone = "0123456789",
                            Role = "User",
                            Username = "bookstoreuser"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "456 Elm St",
                            CCCD = "987654321",
                            Email = "huuvinhhoctap0903@gmail.com",
                            FullName = "Nguyen Huu Vinh",
                            Password = "12345",
                            Phone = "0987654321",
                            Role = "Admin",
                            Username = "bookstoreadmin"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "789 Oak St",
                            CCCD = "456789123",
                            Email = "levanc@example.com",
                            FullName = "Le Van C",
                            Password = "12345",
                            Phone = "0345678912",
                            Role = "User",
                            Username = "levanc"
                        },
                        new
                        {
                            CustomerID = 4,
                            Address = "321 Pine St",
                            CCCD = "654321987",
                            Email = "phamthid@example.com",
                            FullName = "Pham Thi D",
                            Password = "12345",
                            Phone = "0765432198",
                            Role = "User",
                            Username = "phamthid"
                        },
                        new
                        {
                            CustomerID = 5,
                            Address = "987 Maple St",
                            CCCD = "321654987",
                            Email = "hoangvane@example.com",
                            FullName = "Hoang Van E",
                            Password = "12345",
                            Phone = "0891234567",
                            Role = "User",
                            Username = "hoangvane"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("GuestAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            CustomerID = 1,
                            OrderDate = new DateTime(2024, 11, 26, 11, 26, 10, 507, DateTimeKind.Local).AddTicks(6652),
                            OrderStatus = "Pending"
                        },
                        new
                        {
                            OrderID = 2,
                            CustomerID = 2,
                            OrderDate = new DateTime(2024, 11, 26, 11, 26, 10, 508, DateTimeKind.Local).AddTicks(7834),
                            OrderStatus = "Completed"
                        },
                        new
                        {
                            OrderID = 3,
                            CustomerID = 3,
                            OrderDate = new DateTime(2024, 11, 26, 11, 26, 10, 508, DateTimeKind.Local).AddTicks(7854),
                            OrderStatus = "Shipped"
                        },
                        new
                        {
                            OrderID = 4,
                            CustomerID = 4,
                            OrderDate = new DateTime(2024, 11, 26, 11, 26, 10, 508, DateTimeKind.Local).AddTicks(7856),
                            OrderStatus = "Pending"
                        },
                        new
                        {
                            OrderID = 5,
                            CustomerID = 5,
                            OrderDate = new DateTime(2024, 11, 26, 11, 26, 10, 508, DateTimeKind.Local).AddTicks(7857),
                            OrderStatus = "Cancelled"
                        },
                        new
                        {
                            OrderID = 6,
                            GuestAddress = "123 Main St",
                            GuestCCCD = "123456789",
                            GuestEmail = "nguyenvana@example.com",
                            GuestFullName = "Nguyen Van B",
                            GuestPhone = "0123456789",
                            OrderDate = new DateTime(2024, 11, 26, 11, 26, 10, 508, DateTimeKind.Local).AddTicks(7858),
                            OrderStatus = "Completed"
                        },
                        new
                        {
                            OrderID = 7,
                            GuestAddress = "123 Main St",
                            GuestCCCD = "123456789",
                            GuestEmail = "nguyenvana@example.com",
                            GuestFullName = "Nguyen Van B",
                            GuestPhone = "0123456789",
                            OrderDate = new DateTime(2024, 11, 26, 11, 26, 10, 508, DateTimeKind.Local).AddTicks(8535),
                            OrderStatus = "Completed"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("BookID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailID = 1,
                            BookID = 1,
                            OrderID = 1,
                            Price = 39.98m,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailID = 2,
                            BookID = 2,
                            OrderID = 2,
                            Price = 29.99m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailID = 3,
                            BookID = 3,
                            OrderID = 3,
                            Price = 75.00m,
                            Quantity = 3
                        },
                        new
                        {
                            OrderDetailID = 4,
                            BookID = 4,
                            OrderID = 4,
                            Price = 15.50m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailID = 5,
                            BookID = 5,
                            OrderID = 5,
                            Price = 64.95m,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentID = 1,
                            OrderID = 1,
                            PaymentDate = new DateTime(2024, 11, 26, 11, 26, 10, 509, DateTimeKind.Local).AddTicks(592),
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Paid"
                        },
                        new
                        {
                            PaymentID = 2,
                            OrderID = 2,
                            PaymentDate = new DateTime(2024, 11, 26, 11, 26, 10, 509, DateTimeKind.Local).AddTicks(1171),
                            PaymentMethod = "PayPal",
                            PaymentStatus = "Paid"
                        },
                        new
                        {
                            PaymentID = 3,
                            OrderID = 3,
                            PaymentDate = new DateTime(2024, 11, 26, 11, 26, 10, 509, DateTimeKind.Local).AddTicks(1174),
                            PaymentMethod = "Bank Transfer",
                            PaymentStatus = "Pending"
                        },
                        new
                        {
                            PaymentID = 4,
                            OrderID = 4,
                            PaymentDate = new DateTime(2024, 11, 26, 11, 26, 10, 509, DateTimeKind.Local).AddTicks(1175),
                            PaymentMethod = "Cash",
                            PaymentStatus = "Paid"
                        },
                        new
                        {
                            PaymentID = 5,
                            OrderID = 5,
                            PaymentDate = new DateTime(2024, 11, 26, 11, 26, 10, 509, DateTimeKind.Local).AddTicks(1177),
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Failed"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("BookID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            CartID = 1,
                            BookID = 1,
                            CustomerID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            CartID = 2,
                            BookID = 2,
                            CustomerID = 2,
                            Quantity = 2
                        },
                        new
                        {
                            CartID = 3,
                            BookID = 3,
                            CustomerID = 3,
                            Quantity = 1
                        },
                        new
                        {
                            CartID = 4,
                            BookID = 4,
                            CustomerID = 4,
                            Quantity = 3
                        },
                        new
                        {
                            CartID = 5,
                            BookID = 5,
                            CustomerID = 5,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrderDetail", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Payment", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ShoppingCart", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
